### ISSUE TITLE
termadore does not handle SIGINT

### ISSUE THREAD

**Issue by awth13** [bolt-blue/termadore#4]
### Problem
Unless demo code specifies a key to intercept and leave the render loop, there is no way to exit a running `termadore` program cleanly. It would be nice if `termadore` could, at least, handle <kbd>Ctrl-C</kbd> (`SIGINT`).

### Proposed solution
Implement a signal handler in `src`.

**Comment by bolt-blue** [comment]
Thanks. Good point.
I will fix this asap.

**Comment by bolt-blue** [comment]
Have pushed a potential solution to `feature/sigint`.
Any thoughts?

**Comment by bolt-blue** [comment]
Fixed with https://github.com/bolt-blue/termadore/commit/709230a935187edd7ae5f4631058eb8fc63f2ab7
